import type { SupabaseClient } from "@supabase/supabase-js";

const one=<T>(value:T|T[]):T=>Array.isArray(value)?value[0] as T:value;
export interface MarketPlayer { listingId:string;name:string;age:number;position:string;overall:number;askingPrice:number;availableUntil:string; }
export interface LeagueTransferClub { leagueClubId:string;clubName:string; }
export interface OfferOutcome { offerId:string;status:"PENDING"|"ACCEPTED"|"REJECTED"|"COUNTERED";counterAmount:number|null; }
export interface TransferTarget { clubPlayerId:string;name:string;clubName:string;position:string;overall:number;marketValue:number; }
export interface IncomingOffer { offerId:string;buyerClub:string;playerName:string;position:string;overall:number;amount:number;expiresAt:string; }
export interface TransferNotification { offerId:string;playerName:string;amount:number;buyerClub:string;sellerClub:string;buyerClubId:string;sellerClubId:string;buyerTelegramId:number|null;sellerTelegramId:number|null;counterAmount:number|null; }

export class TransferRepository {
 constructor(private readonly database:SupabaseClient){}
 async market(userId:string,buyerClubId:string,page=0,pageSize=8,group="ALL"):Promise<MarketPlayer[]>{
  const owner=await this.ownerLeague(userId,buyerClubId);const{data,error}=await this.database.from("global_market_listings").select("id,asking_price,available_until,seller_club_id,club_players!inner(league_club_id,players!inner(short_name,age,primary_position,player_attributes!inner(overall)),league_clubs!inner(league_instance_id))").eq("status","ACTIVE").gt("available_until",new Date().toISOString()).order("asking_price");if(error)throw error;
  const groups:Record<string,string[]>={GK:["GK"],DEF:["CB","LB","RB","LWB","RWB"],MID:["CDM","CM","CAM","LM","RM"],ATT:["ST","CF","LW","RW"]};return(data??[]).filter((row:any)=>{const player=one<any>(row.club_players),position=one<any>(player.players).primary_position;return row.seller_club_id!==buyerClubId&&player.league_club_id!==buyerClubId&&player.league_club_id===row.seller_club_id&&one<any>(player.league_clubs).league_instance_id===owner.league_instance_id&&(!groups[group]||groups[group]!.includes(position));}).map((row:any)=>{const p=one<any>(one<any>(row.club_players).players);return{listingId:row.id,name:p.short_name,age:p.age,position:p.primary_position,overall:one<any>(p.player_attributes).overall,askingPrice:Number(row.asking_price),availableUntil:row.available_until};}).sort((a,b)=>b.overall-a.overall||a.askingPrice-b.askingPrice).slice(page*pageSize,(page+1)*pageSize);
 }
 async listing(userId:string,buyerClubId:string,id:string):Promise<MarketPlayer|null>{for(const group of["ALL","GK","DEF","MID","ATT"]){const item=(await this.market(userId,buyerClubId,0,500,group)).find(player=>player.listingId===id);if(item)return item;}return null;}
 async buy(userId:string,buyerClubId:string,listingId:string):Promise<OfferOutcome>{
  const listing=await this.listing(userId,buyerClubId,listingId);if(!listing)throw new Error("LISTING_NOT_AVAILABLE");const{data:l,error:le}=await this.database.from("global_market_listings").select("asking_price,club_player_id").eq("id",listingId).eq("status","ACTIVE").gt("available_until",new Date().toISOString()).single();if(le)throw le;
  const{data,error}=await this.database.rpc("create_transfer_offer",{p_user_id:userId,p_buyer_club_id:buyerClubId,p_club_player_id:l.club_player_id,p_amount:l.asking_price});if(error)throw error;const r=data?.[0];return{offerId:r.offer_id,status:r.status,counterAmount:r.counter_amount?Number(r.counter_amount):null};
 }
 async saleCandidates(userId:string,clubId:string):Promise<TransferTarget[]>{const{data,error}=await this.database.from("club_players").select("id,resale_locked_until,players!inner(short_name,primary_position,market_value,player_attributes!inner(overall)),league_clubs!inner(manager_user_id,clubs!inner(name))").eq("league_club_id",clubId).eq("league_clubs.manager_user_id",userId);if(error)throw error;return(data??[]).filter((row:any)=>!row.resale_locked_until||new Date(row.resale_locked_until)<=new Date()).map((row:any)=>{const player=one<any>(row.players),club=one<any>(one<any>(row.league_clubs).clubs);return{clubPlayerId:row.id,name:player.short_name,clubName:club.name,position:player.primary_position,overall:one<any>(player.player_attributes).overall,marketValue:Number(player.market_value)}}).sort((a,b)=>b.overall-a.overall);}
 async leagueClubs(userId:string,clubId:string):Promise<LeagueTransferClub[]>{const owner=await this.ownerLeague(userId,clubId);const{data,error}=await this.database.from("league_clubs").select("id,clubs!inner(name)").eq("league_instance_id",owner.league_instance_id).neq("id",clubId).order("clubs(name)");if(error)throw error;return(data??[]).map((row:any)=>({leagueClubId:row.id,clubName:one<any>(row.clubs).name}));}
 async clubTargets(userId:string,clubId:string,targetClubId:string,page=0,pageSize=25):Promise<TransferTarget[]>{const owner=await this.ownerLeague(userId,clubId);if(targetClubId===clubId)throw new Error("OWN_CLUB");const{data:target,error:targetError}=await this.database.from("league_clubs").select("id,league_instance_id,clubs!inner(name)").eq("id",targetClubId).maybeSingle();if(targetError||!target||target.league_instance_id!==owner.league_instance_id)throw new Error("TARGET_CLUB_INVALID");const from=page*pageSize;const{data,error}=await this.database.from("club_players").select("id,resale_locked_until,players!inner(short_name,primary_position,market_value,player_attributes!inner(overall))").eq("league_club_id",targetClubId).range(from,from+pageSize-1);if(error)throw error;const clubName=one<any>((target as any).clubs).name;return(data??[]).filter((row:any)=>!row.resale_locked_until||new Date(row.resale_locked_until)<=new Date()).map((row:any)=>{const player=one<any>(row.players);return{clubPlayerId:row.id,name:player.short_name,clubName,position:player.primary_position,overall:one<any>(player.player_attributes).overall,marketValue:Number(player.market_value)}}).sort((a,b)=>b.overall-a.overall);}
 async leagueTargets(userId:string,clubId:string,page=0,pageSize=10):Promise<TransferTarget[]>{const{data:owner,error:ownerError}=await this.database.from("league_clubs").select("league_instance_id").eq("id",clubId).eq("manager_user_id",userId).maybeSingle();if(ownerError||!owner)throw new Error("CLUB_NOT_OWNED");const from=page*pageSize;const{data,error}=await this.database.from("club_players").select("id,league_club_id,resale_locked_until,players!inner(short_name,primary_position,market_value,player_attributes!inner(overall)),league_clubs!inner(league_instance_id,clubs!inner(name))").eq("league_clubs.league_instance_id",owner.league_instance_id).neq("league_club_id",clubId).range(from,from+pageSize-1);if(error)throw error;return(data??[]).filter((row:any)=>row.league_club_id!==clubId&&(!row.resale_locked_until||new Date(row.resale_locked_until)<=new Date())).map((row:any)=>{const player=one<any>(row.players),club=one<any>(one<any>(row.league_clubs).clubs);return{clubPlayerId:row.id,name:player.short_name,clubName:club.name,position:player.primary_position,overall:one<any>(player.player_attributes).overall,marketValue:Number(player.market_value)}}).sort((a,b)=>b.overall-a.overall);}
 async listForSale(userId:string,clubId:string,clubPlayerId:string,askingPrice:number):Promise<void>{const candidates=await this.saleCandidates(userId,clubId);if(!candidates.some(player=>player.clubPlayerId===clubPlayerId))throw new Error("PLAYER_NOT_AVAILABLE");const{count,error:countError}=await this.database.from("club_players").select("id",{count:"exact",head:true}).eq("league_club_id",clubId);if(countError)throw countError;if((count??0)<=18)throw new Error("SELLER_MIN_SQUAD");const{error}=await this.database.from("global_market_listings").insert({club_player_id:clubPlayerId,seller_club_id:clubId,asking_price:askingPrice});if(error)throw error;}
 async offer(userId:string,buyerClubId:string,clubPlayerId:string,amount:number):Promise<OfferOutcome>{const{data,error}=await this.database.rpc("create_transfer_offer",{p_user_id:userId,p_buyer_club_id:buyerClubId,p_club_player_id:clubPlayerId,p_amount:amount});if(error)throw error;const result=data?.[0];return{offerId:result.offer_id,status:result.status,counterAmount:result.counter_amount?Number(result.counter_amount):null};}
 async incomingOffers(userId:string,clubId:string):Promise<IncomingOffer[]>{const{data:club,error:clubError}=await this.database.from("league_clubs").select("id").eq("id",clubId).eq("manager_user_id",userId).maybeSingle();if(clubError||!club)throw new Error("CLUB_NOT_OWNED");const{data,error}=await this.database.from("transfer_offers").select("id,buyer_club_id,club_player_id,amount,expires_at").eq("seller_club_id",clubId).eq("status","PENDING").order("created_at",{ascending:false});if(error)throw error;const offers=data??[];if(!offers.length)return[];const playerIds=offers.map((row:any)=>row.club_player_id),buyerIds=offers.map((row:any)=>row.buyer_club_id);const[playersResult,buyersResult]=await Promise.all([this.database.from("club_players").select("id,players!inner(short_name,primary_position,player_attributes!inner(overall))").in("id",playerIds),this.database.from("league_clubs").select("id,clubs!inner(name)").in("id",buyerIds)]);if(playersResult.error)throw playersResult.error;if(buyersResult.error)throw buyersResult.error;const players=new Map((playersResult.data??[]).map((row:any)=>{const p=one<any>(row.players);return[row.id,p];})),buyers=new Map((buyersResult.data??[]).map((row:any)=>[row.id,one<any>(row.clubs).name]));return offers.map((row:any)=>{const p=players.get(row.club_player_id);return{offerId:row.id,buyerClub:buyers.get(row.buyer_club_id)??"Noma’lum klub",playerName:p?.short_name??"Futbolchi",position:p?.primary_position??"",overall:p?one<any>(p.player_attributes).overall:0,amount:Number(row.amount),expiresAt:row.expires_at};});}
 async respondToOffer(userId:string,offerId:string,decision:"ACCEPT"|"REJECT"):Promise<string>{const{data,error}=await this.database.rpc("respond_transfer_offer",{p_user_id:userId,p_offer_id:offerId,p_decision:decision,p_counter:null});if(error)throw error;return String(data);}
 async counterOffer(userId:string,offerId:string,amount:number):Promise<string>{const{data,error}=await this.database.rpc("respond_transfer_offer",{p_user_id:userId,p_offer_id:offerId,p_decision:"COUNTER",p_counter:amount});if(error)throw error;return String(data);}
 async acceptCounterOffer(userId:string,offerId:string):Promise<void>{const{error}=await this.database.rpc("accept_counter_offer",{p_user_id:userId,p_offer_id:offerId});if(error)throw error;}
 async notification(offerId:string):Promise<TransferNotification|null>{const{data:offer,error}=await this.database.from("transfer_offers").select("id,buyer_club_id,seller_club_id,club_player_id,amount,counter_amount").eq("id",offerId).maybeSingle();if(error)throw error;if(!offer)return null;const[clubsResult,playerResult]=await Promise.all([this.database.from("league_clubs").select("id,manager_user_id,clubs!inner(name)").in("id",[offer.buyer_club_id,offer.seller_club_id]),this.database.from("club_players").select("players!inner(short_name)").eq("id",offer.club_player_id).maybeSingle()]);if(clubsResult.error)throw clubsResult.error;if(playerResult.error)throw playerResult.error;const clubs=new Map((clubsResult.data??[]).map((row:any)=>[row.id,{name:one<any>(row.clubs).name,userId:row.manager_user_id}]));const ids=[...new Set([...clubs.values()].map(c=>c.userId).filter(Boolean))];const{data:people,error:peopleError}=ids.length?await this.database.from("users").select("id,telegram_id").in("id",ids):{data:[],error:null};if(peopleError)throw peopleError;const telegram=new Map((people??[]).map((row:any)=>[row.id,row.telegram_id]));const buyer=clubs.get(offer.buyer_club_id),seller=clubs.get(offer.seller_club_id);return{offerId:offer.id,playerName:one<any>((playerResult.data as any)?.players).short_name,amount:Number(offer.amount),counterAmount:offer.counter_amount?Number(offer.counter_amount):null,buyerClub:buyer?.name??"Klub",sellerClub:seller?.name??"Klub",buyerClubId:offer.buyer_club_id,sellerClubId:offer.seller_club_id,buyerTelegramId:buyer?.userId?telegram.get(buyer.userId)??null:null,sellerTelegramId:seller?.userId?telegram.get(seller.userId)??null:null};}
 private async ownerLeague(userId:string,clubId:string):Promise<{league_instance_id:string}>{const{data,error}=await this.database.from("league_clubs").select("league_instance_id").eq("id",clubId).eq("manager_user_id",userId).maybeSingle();if(error||!data)throw new Error("CLUB_NOT_OWNED");return data;}
 async maintain():Promise<void>{
  const now=new Date().toISOString();await this.database.rpc("expire_transfer_offers");
  const{error}=await this.database.from("global_market_listings").update({status:"EXPIRED"}).eq("status","ACTIVE").lte("available_until",now);if(error)throw error;
  const{count}=await this.database.from("global_market_listings").select("id",{count:"exact",head:true}).eq("status","ACTIVE");
  const needed=Math.max(0,80-(count??0));if(!needed)return;
  const{data:expired,error:expiredError}=await this.database.from("global_market_listings").select("id").eq("status","EXPIRED").limit(needed);if(expiredError)throw expiredError;
  if(expired?.length){const until=new Date(Date.now()+24*60*60*1000).toISOString();const{error:refreshError}=await this.database.from("global_market_listings").update({status:"ACTIVE",available_until:until}).in("id",expired.map(row=>row.id));if(refreshError)throw refreshError;}
 }
}
