import type{SupabaseClient}from"@supabase/supabase-js";
export interface ManagerProfile{name:string;username:string|null;rating:number;matches:number;wins:number;draws:number;losses:number;titles:number;seasons:number;spend:number;income:number;biggest:number;}
export interface Sponsor{id:string;name:string;payment:number;channelId:number|null;channelUsername:string|null;joinUrl:string|null;}
export class ProgressionRepository{constructor(private readonly database:SupabaseClient){}
 async profile(userId:string):Promise<ManagerProfile>{const{data,error}=await this.database.from("manager_profiles").select("manager_rating,matches,wins,draws,losses,titles,seasons,total_transfer_spend,total_transfer_income,biggest_transfer,users!inner(first_name,username)").eq("user_id",userId).single();if(error)throw error;const u=Array.isArray((data as any).users)?(data as any).users[0]:(data as any).users;return{name:u.first_name,username:u.username,rating:data.manager_rating,matches:data.matches,wins:data.wins,draws:data.draws,losses:data.losses,titles:data.titles,seasons:data.seasons,spend:Number(data.total_transfer_spend),income:Number(data.total_transfer_income),biggest:Number(data.biggest_transfer)};}
 async leaderboard(limit=20):Promise<ManagerProfile[]>{const{data,error}=await this.database.from("manager_profiles").select("manager_rating,matches,wins,draws,losses,titles,seasons,total_transfer_spend,total_transfer_income,biggest_transfer,users!inner(first_name,username)").order("manager_rating",{ascending:false}).order("wins",{ascending:false}).limit(limit);if(error)throw error;return(data??[]).map((r:any)=>{const u=Array.isArray(r.users)?r.users[0]:r.users;return{name:u.first_name,username:u.username,rating:r.manager_rating,matches:r.matches,wins:r.wins,draws:r.draws,losses:r.losses,titles:r.titles,seasons:r.seasons,spend:Number(r.total_transfer_spend),income:Number(r.total_transfer_income),biggest:Number(r.biggest_transfer)};});}
 async sponsors():Promise<Sponsor[]>{const{data,error}=await this.database.from("sponsors").select("id,name,payment_per_match,required_channel_id,required_channel_username,join_url").eq("is_active",true).order("payment_per_match");if(error)throw error;return(data??[]).map((s:any)=>({id:s.id,name:s.name,payment:Number(s.payment_per_match),channelId:s.required_channel_id?Number(s.required_channel_id):null,channelUsername:s.required_channel_username,joinUrl:s.join_url}));}
 async acceptSponsor(userId:string,clubId:string,sponsorId:string):Promise<void>{const{error}=await this.database.rpc("accept_sponsor",{p_user_id:userId,p_league_club_id:clubId,p_sponsor_id:sponsorId});if(error)throw error;}
 async setEligibility(userId:string,clubId:string,eligible:boolean):Promise<void>{const{error}=await this.database.rpc("update_sponsor_eligibility",{p_user_id:userId,p_league_club_id:clubId,p_eligible:eligible});if(error)throw error;}
}
